---
apiVersion: "ran.openshift.io/v1"
kind: "SiteConfig"
metadata:
  name: "prod-cluster"
  namespace: "test-cluster"
spec:
  baseDomain: "odine.com"
  clusterImageSetNameRef: "odine-image-001"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD D1n8nRj0NfJfJ9pG0DzvN0DH7x+7rS5lVWZc0d0lTgLGH2YS0w0K5tBVkZD0g0KsO1j5zC2pF6VYi6Y0UjafvT3wGeHh7sM5aFpsdSvdF+7Iu4LThJrLb5Hn1m2FJ63pNzs4D9xmqPjR6i1WND0QTFVtM8rZ1yWRJbo5dNl1p3m7x3MpAmVQqxgR0K8sM5mU9Bz3o7ycYZttZ7a4g4mB9zZs1S8WwfkqU4Qdbp0x6Kps4pupmKL0k/cWuQsH5U/8LJbJwcE3kZ4HCxn/9dTGyPMQ6k2hCaqFAPvXOj5hXykRSPwuhDFMgEuIm2m6WxU2KnT2p0G5QXRnbW8sCiDXfQ dummy@example"
  pullSecretRef:
    name: "odine/secrets/netas-secret.yaml"
  clusters:
  - clusterName: "prod-cluster"
    extraManifestPath: "odine/policies/"
    extraManifests:
      filter:
        inclusionDefault: "exclude"
        include:
        - "netas-site.yaml"
    networkType: "OVNKubernetes"
    clusterLabels:
      location: "ankara"
      type: "bare-metal"
      application: "cnf"
    clusterNetwork:
    - cidr: "10.10.55.12/24"
      hostPrefix: 24
    machineNetwork:
    - cidr: "10.10.22.1/24"
    apiVIP: "10.10.212.25"
    ingressVIP: "10.10.212.5"
    serviceNetwork:
    - "10.24.24.35/24"
    - "10.24.24.32/8"
    additionalNTPSources:
    - "10.212.21.0"
    - "ntp.pool.org"
    nodes:
    - hostName: "odine.master.org"
      role: "master"
      bmcAddress: "192.168.65.3"
      bmcCredentialsName:
        name: "bmc-credentials-0"
      nodeLabels:
        storage: "zte"
        mode: "master"
        location: "ankara"
        vendor: "dell"
      bootMode: "UEFISecureBoot"
      rootDeviceHints:
        vendor: "ZTE"
        deviceName: "/dev/sda"
        size: 90
      bootMACAddress: "AA:3F:92:1B:C4:7E"
      nodeNetwork:
        interfaces:
        - name: "ens1f0"
          macAddress: "04:32:01:52:74:70"
        - name: "ens1f1"
          macAddress: "04:32:01:52:74:71"
        - name: "ens2f0"
          macAddress: "C4:CB:E1:B5:89:01"
        config:
          interfaces:
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens1f1"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "ens2f0"
            state: "up"
            type: "ethernet"
            mtu: 9000
          - ipv4:
              enabled: false
            link-aggregation:
              mode: "balance-tlb"
              port:
              - "ens1f0: 04:32:01:52:74:70"
              - "ens2f0: C4:CB:E1:B5:89:01"
              - "ens1f1: 04:32:01:52:74:71"
              options:
                miimon: "100"
            ipv6:
              enabled: false
            name: "bond0"
            description: "Bond0"
            state: "up"
            type: "bond"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 401
            ipv4:
              address:
                prefix-length: "8"
                ip: "12.12.12.24"
              enabled: true
            ipv6:
              enabled: false
            name: "bond0.401"
            state: "up"
            type: "vlan"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 400
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond0.400"
            state: "up"
            type: "vlan"
            mtu: 9000
          - vlan:
              base-iface: "bond0"
              id: 402
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            name: "bond0.402"
            state: "up"
            type: "vlan"
            mtu: 9000
          dns-resolver:
            config:
              server:
              - "8.8.8.8"
          routes:
            config:
            - next-hop-interface: "bond0.401"
              destination: "0.0.0.0/0"
              next-hop-address: "12.12.12.24"